yarnPath: .yarn/releases/yarn-3.1.1.cjs
caFilePath: .zscalercerts/zscalerrootcert.pem
enableStrictSsl: true
nodeLinker: node-modules
npmRegistryServer: "https://repo.mutualofomaha.com/artifactory/api/npm/npmjs/"